[python]
pyenv_version_name=true

[cmake]
disabled = true

[java]
disabled = true

[character]
success_symbol = "[â¯](purple)"


[cmd_duration]
min_time = 10_000

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
